--Modify PAYLOAD_BLOB Column to BLOB
ALTER TABLE NOMINAL_ROLL_SAGA
    ADD (
        PAYLOAD_BLOB BLOB
        ) LOB (PAYLOAD_BLOB) STORE AS PAYLOAD_BLOB (TABLESPACE API_PEN_BLOB_DATA);
UPDATE NOMINAL_ROLL_SAGA SET PAYLOAD_BLOB = UTL_RAW.CAST_TO_RAW(PAYLOAD);
ALTER TABLE NOMINAL_ROLL_SAGA DROP COLUMN PAYLOAD;
ALTER TABLE NOMINAL_ROLL_SAGA RENAME COLUMN PAYLOAD_BLOB TO PAYLOAD;
ALTER TABLE NOMINAL_ROLL_SAGA
    MODIFY (
        PAYLOAD NOT NULL
        );

--Modify SAGA_EVENT_RESPONSE_BLOB Column to BLOB
ALTER TABLE NOMINAL_ROLL_SAGA_EVENT_STATES
    ADD (
        SAGA_EVENT_RESPONSE_BLOB BLOB
        ) LOB (SAGA_EVENT_RESPONSE_BLOB) STORE AS SAGA_EVENT_RESPONSE_BLOB (TABLESPACE API_PEN_BLOB_DATA);
UPDATE NOMINAL_ROLL_SAGA_EVENT_STATES SET SAGA_EVENT_RESPONSE_BLOB = UTL_RAW.CAST_TO_RAW(SAGA_EVENT_RESPONSE);
ALTER TABLE NOMINAL_ROLL_SAGA_EVENT_STATES DROP COLUMN SAGA_EVENT_RESPONSE;
ALTER TABLE NOMINAL_ROLL_SAGA_EVENT_STATES RENAME COLUMN SAGA_EVENT_RESPONSE_BLOB TO SAGA_EVENT_RESPONSE;
ALTER TABLE NOMINAL_ROLL_SAGA_EVENT_STATES
    MODIFY (
        SAGA_EVENT_RESPONSE NOT NULL
        );
