CREATE TABLE NOMINAL_ROLL_SAGA
(
    SAGA_ID                 RAW(16)              NOT NULL,
    NOMINAL_ROLL_STUDENT_ID RAW(16),
    SAGA_NAME               VARCHAR2(50)         NOT NULL,
    SAGA_STATE              VARCHAR2(100)        NOT NULL,
    PAYLOAD                 VARCHAR2(4000)       NOT NULL,
    STATUS                  VARCHAR2(20)         NOT NULL,
    CREATE_USER             VARCHAR2(32)         NOT NULL,
    CREATE_DATE             DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER             VARCHAR2(32)         NOT NULL,
    UPDATE_DATE             DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT NOMINAL_ROLL_SAGA_PK PRIMARY KEY (SAGA_ID)
) TABLESPACE API_PEN_BLOB_DATA;
CREATE INDEX NOMINAL_ROLL_SAGA_STATUS_IDX ON NOMINAL_ROLL_SAGA (STATUS) TABLESPACE API_PEN_IDX;
CREATE INDEX NOMINAL_ROLL_SAGA_NR_STUDENT_ID_IDX ON NOMINAL_ROLL_SAGA (NOMINAL_ROLL_STUDENT_ID) TABLESPACE API_PEN_IDX;

CREATE TABLE NOMINAL_ROLL_SAGA_EVENT_STATES
(
    SAGA_EVENT_ID       RAW(16)              NOT NULL,
    SAGA_ID             RAW(16)              NOT NULL,
    SAGA_EVENT_STATE    VARCHAR2(100)        NOT NULL,
    SAGA_EVENT_OUTCOME  VARCHAR2(100)        NOT NULL,
    SAGA_STEP_NUMBER    NUMBER(4)            NOT NULL,
    SAGA_EVENT_RESPONSE VARCHAR2(4000)       NOT NULL,
    CREATE_USER         VARCHAR2(32)         NOT NULL,
    CREATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER         VARCHAR2(32)         NOT NULL,
    UPDATE_DATE         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT NOMINAL_ROLL_SAGA_EVENT_STATES_PK PRIMARY KEY (SAGA_EVENT_ID)
) TABLESPACE API_PEN_BLOB_DATA;
CREATE INDEX NOMINAL_ROLL_SAGA_EVENT_STATES_IDSOS_IDX ON NOMINAL_ROLL_SAGA_EVENT_STATES (SAGA_ID, SAGA_EVENT_STATE, SAGA_EVENT_OUTCOME, SAGA_STEP_NUMBER) TABLESPACE API_PEN_IDX;
ALTER TABLE NOMINAL_ROLL_SAGA_EVENT_STATES
    ADD CONSTRAINT NOMINAL_ROLL_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES NOMINAL_ROLL_SAGA (SAGA_ID);

CREATE TABLE NOMINAL_ROLL_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT NOMINAL_ROLL_SHEDLOCK_PK PRIMARY KEY (NAME)
);
COMMENT ON TABLE NOMINAL_ROLL_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

CREATE INDEX NOMINAL_ROLL_POSTED_STUDENT_DEMOG_IDX ON NOMINAL_ROLL_POSTED_STUDENT (SURNAME, GIVEN_NAMES, GENDER, BIRTH_DATE, GRADE) TABLESPACE API_PEN_IDX;
