CREATE TABLE NOMINAL_ROLL_EVENT
(
    EVENT_ID      RAW(16)                             NOT NULL,
    EVENT_PAYLOAD BLOB                                NOT NULL,
    EVENT_STATUS  VARCHAR2(50)                        NOT NULL,
    EVENT_TYPE    VARCHAR2(100)                       NOT NULL,
    SAGA_ID       RAW(16),
    EVENT_OUTCOME VARCHAR2(100)                       NOT NULL,
    REPLY_CHANNEL VARCHAR2(100),
    CREATE_USER   VARCHAR(32)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(32)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT NOMINAL_ROLL_EVENT_EVENT_PK PRIMARY KEY (EVENT_ID)
) TABLESPACE API_PEN_BLOB_DATA;

CREATE INDEX NOMINAL_ROLL_EVENT_EVENT_STATUS_IDX ON NOMINAL_ROLL_EVENT (EVENT_STATUS);
CREATE INDEX NOMINAL_ROLL_EVENT_EVENT_TYPE_IDX ON NOMINAL_ROLL_EVENT (EVENT_TYPE);