CREATE TABLE FED_BAND_CODE
(
    FED_BAND_CODE_ID   UUID                             NOT NULL,
    SCHOOL_ID          UUID                             NOT NULL,
    FED_BAND_CODE      VARCHAR(10)                      NOT NULL,
    CREATE_USER     VARCHAR(32)                         NOT NULL,
    CREATE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER     VARCHAR(32)                         NOT NULL,
    UPDATE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FED_BAND_CODE_ID_PK PRIMARY KEY (FED_BAND_CODE_ID),
    CONSTRAINT UNQ_FED_BAND_CODE UNIQUE (FED_BAND_CODE)

);

ALTER TABLE FED_BAND_CODE
    ADD CONSTRAINT UNQ_FED_BAND_CODE_SCHOOL_ID UNIQUE (SCHOOL_ID);