CREATE TABLE NOMINAL_ROLL_STUDENT
(
    NOMINAL_ROLL_STUDENT_ID RAW(16)              NOT NULL,
    SCHOOL_DISTRICT_NUMBER  VARCHAR2(500),
    SCHOOL_NUMBER           VARCHAR2(500),
    SCHOOL_NAME             VARCHAR2(500),
    LEA_PROVINCIAL          VARCHAR2(500),
    RECIPIENT_NUMBER        VARCHAR2(500),
    RECIPIENT_NAME          VARCHAR2(500),
    IDENTITY                VARCHAR2(500),
    SURNAME                 VARCHAR2(500),
    GIVEN_NAMES             VARCHAR2(500),
    INITIALS                VARCHAR2(500),
    GENDER                  VARCHAR2(500),
    BIRTH_DATE              VARCHAR2(500),
    GRADE                   VARCHAR2(500),
    FTE                     VARCHAR2(500),
    BAND_OF_RESIDENCE       VARCHAR2(500),
    ASSIGNED_PEN            VARCHAR2(9),
    STATUS                  VARCHAR2(20),
    CREATE_USER             VARCHAR2(32)         NOT NULL,
    CREATE_DATE             DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER             VARCHAR2(32)         NOT NULL,
    UPDATE_DATE             DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT NOMINAL_ROLL_STUDENT_PK PRIMARY KEY (NOMINAL_ROLL_STUDENT_ID)
) TABLESPACE API_PEN_DATA;

CREATE INDEX NOMINAL_ROLL_STUDENT_STATUS_IDX ON NOMINAL_ROLL_STUDENT (STATUS) TABLESPACE API_PEN_IDX;

CREATE TABLE NOMINAL_ROLL_STUDENT_VALIDATION_ERROR
(
    NOMINAL_ROLL_STUDENT_VALIDATION_ID RAW(16)              NOT NULL,
    NOMINAL_ROLL_STUDENT_ID            RAW(16)              NOT NULL,
    FIELD_NAME                         VARCHAR2(50)         NOT NULL,
    FIELD_ERROR                        VARCHAR2(200)        NOT NULL,
    CREATE_USER                        VARCHAR2(32)         NOT NULL,
    CREATE_DATE                        DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER                        VARCHAR2(32)         NOT NULL,
    UPDATE_DATE                        DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT NOMINAL_ROLL_STUDENT_VALIDATION_ERROR_PK PRIMARY KEY (NOMINAL_ROLL_STUDENT_VALIDATION_ID)
) TABLESPACE API_PEN_DATA;

ALTER TABLE NOMINAL_ROLL_STUDENT_VALIDATION_ERROR
    ADD CONSTRAINT NOMINAL_ROLL_STUDENT_VALIDATION_ERROR_NOMINAL_ROLL_STUDENT_ID_FK FOREIGN KEY (NOMINAL_ROLL_STUDENT_ID) REFERENCES NOMINAL_ROLL_STUDENT (NOMINAL_ROLL_STUDENT_ID);

CREATE INDEX NOMINAL_ROLL_STUDENT_VE_NRSID_IDX ON NOMINAL_ROLL_STUDENT_VALIDATION_ERROR (NOMINAL_ROLL_STUDENT_ID) TABLESPACE API_PEN_IDX;
