ALTER TABLE NOMINAL_ROLL_SAGA
    DROP CONSTRAINT NOMINAL_ROLL_STUDENT_ID_SAGA_NAME_UK;

ALTER TABLE NOMINAL_ROLL_SAGA
    ADD CONSTRAINT PROCESSING_YEAR_NOMINAL_ROLL_STUDENT_ID_SAGA_NAME_UK UNIQUE (PROCESSING_YEAR, NOMINAL_ROLL_STUDENT_ID, SAGA_NAME);
